url: "https://olefriis.github.io"
baseurl: ""
title: "My Time as a Human Being"
description: "Computers, retro gaming, running, and baking. Maybe not interesting to others."

theme: jekyll-theme-slate
plugins:
  - jekyll-feed